### ISSUE TITLE
Integration conflict due bundled GSON library

### ISSUE THREAD

**Issue by gpinigin** [streamroot/android#2]
*Description*
StreamrootSDK contains bundled GSON library conflicting with another one set up as dependency in a project.

*Possible solution*
* Change the package name of bundled GSON library
* Use GSON library as external dependency

**Comment by pedronveloso** [comment]
Hi @gpinigin 

Nowadays Gradle has gotten pretty good at handling dependency conflicts, and for that reason a lot of libraries ship with dependencies that the applications already have. I tried to replicate the problem by including an older version of GSON on my gradle build configuration and it handled it correctly (basically updates the older to the most current of all the dependencies). Could you possibly share the error message you're getting?

And also, could you please share the output of this command on the configuration that fails to build? Run it from your project's root:

`./gradlew app:dependencies`

Note: Replace `app` with the actual name of your project

Thank you in advance.

**Comment by jlouazel** [comment]
We now provide a way to install the SDK through gradle. Look at the [documentation](https://streamroot.readme.io/docs/android-sdk) for updated samples. Tested on this repository, it fixes the issues.
