### ISSUE TITLE
Resources conflict with IMA SDK 3.4.0 for Android 

### ISSUE THREAD

**Issue by gpinigin** [streamroot/android#3]
*Description*
Both StreamrootSDK and IMA SDK contains nanohttpd as bundled dependency.

Conflicting files:
- "META-INF/nanohttpd/default-mimetypes.properties"
- "META-INF/nanohttpd/mimetypes.properties"

What helps me — remove of conflicting files from "StreamrootSDK.aar/classes.jar"

**Comment by jlouazel** [comment]
Fixed with SDK version 1.4.x. Look at the updated [documentation](https://streamroot.readme.io/docs/android-sdk).

**Comment by demo1232** [comment]
I have used JW Player SDK for a video player that is working fine on Android. But now want to add pre-roll advertisement using on Google IMA Advertisement in Android. I have added all the code related to Ads also added dependencies build.Gradle file.
JW Player SDK
compile 'com.longtailvideo.jwplayer:jwplayer-android-sdk:+'
Google IMA Advertisment SDK
'compile 'com.longtailvideo.jwplayer:jwplayer-ima:+'

But I am getting the error when going to run the application from Android studio.
Below are the error which getting at the time of run the application:-

Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/nanohttpd/mimetypes.properties
File1: C:\Users\gauravkumar.singh\.gradle\caches\modules-2\files-2.1\com.google.ads.interactivemedia.v3\interactivemedia\3.5.2\21246e1a6815dc499443d46f9f5dbe954fd2b746\interactivemedia-3.5.2.jar
File2: C:\Users\gauravkumar.singh\.android\build-cache\fe94083f69d19de3fbe36d97989e4bfe87efb104\output\jars\classes.jar

I do not understand how to resolve it.Please help us ASAP.
