### ISSUE TITLE
JS error TypeError: Object [object Array] has no method 'findIndex' on sample stream

### ISSUE THREAD

**Issue by gpinigin** [streamroot/android#4]
Device fingerprint
samsung/t03gxx/t03g:4.4.2/KOT49H/N7100XXUFNE1:user/release-keys

[Log output](https://drive.google.com/file/d/0B79Q74izPXkcVkQxYnM4TklVb0U/view?usp=sharing)

**Comment by jlouazel** [comment]
Should be fixed with SDK `v1.4.x`. Will reopen this one if it happens again.
